---
title: "Analisis"
output:
  html_document:
    toc: yes
    toc_depth: '5'
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: 5
    highlight: tango
linestretch: 1.3
classoption: fleqn
header-includes:
- \setlength{\mathindent}{0pt}
- \setlength\parindent{0pt}
---

 


```{r include=FALSE}



library(survival)
library(survminer)
library(utils)
library(InformationValue)
library(questionr)
library(knitr)
library(ggsci)
library(forestmodel)
if (!(require(meta))){
install.packages("meta")
}
library(odytools)
library(labelled)
library(kableExtra)
library(gt)
library(gtsummary)
library(haven)

data <- read.csv2("EFS_RFS.csv") 
data$Survival.time <- as.numeric(data$Survival.time)
data$y_rfs <- Surv(data$Survival.time,data$Status)


```



\newpage

# Paper 5

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "5",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "5",],
           title = " ",
           pval = F, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=5,
          surv.median.line="hv",
          xlim=c(0,29))





```



\newpage

# Paper 6

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "6",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "6",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=10,
          surv.median.line="hv",
          xlim=c(0,50))





```




\newpage

# Paper 8

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "8",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "8",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=5,
          surv.median.line="hv",
          xlim=c(0,38))





```



\newpage

# Paper 10

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "10",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "10",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=3,
          surv.median.line="hv",
          xlim=c(0,32))





```



\newpage

# Paper 11

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "11",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "11",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=6,
          surv.median.line="hv",
          xlim=c(0,37))





```






\newpage

# Paper 12

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "12",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "12",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=1,
          surv.median.line="hv",
          xlim=c(0,23))





```




\newpage

# Paper 15

```{r echo=FALSE, fig.height=8, fig.width=14, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "15",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "15",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=2,
          surv.median.line="hv",
          xlim=c(0,34))





```




\newpage

# Paper 16

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "16",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "16",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=20,
          surv.median.line="hv",
          xlim=c(0,80))





```




\newpage

# Paper 17

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "17",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "17",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=6.6,
          surv.median.line="hv",
          xlim=c(0,40))





```




\newpage

# Paper 18

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~1,data=data[data$Paper == "18",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "18",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=2,
          surv.median.line="hv",
          xlim=c(0,19))





```





\newpage

# Paper 19

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "19",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "19",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=10,
          surv.median.line="hv",
          xlim=c(0,40))





```




\newpage

# Paper 21

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "21",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "21",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=5,
          surv.median.line="hv",
          xlim=c(0,25))





```






\newpage

# Paper 22

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "22",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "22",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=6,
          surv.median.line="hv",
          xlim=c(0,48))





```




\newpage

# Paper 24

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "24",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "24",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=3,
          surv.median.line="hv",
          xlim=c(0,24))





```




\newpage

# Paper 29

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "29",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "29",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=6,
          surv.median.line="hv",
          xlim=c(0,36))





```



\newpage

# Paper 30

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "30",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "30",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=10,
          surv.median.line="hv",
          xlim=c(0,60))





```





\newpage

# Paper 31

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "31",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "31",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=2,
          surv.median.line="hv",
          xlim=c(0,23))





```



\newpage

# Paper 34

```{r echo=FALSE, fig.height=8, fig.width=11, message=FALSE, warning=FALSE}


surv1 <- survfit(y_rfs~Subgroup,data=data[data$Paper == "34",])

t1 <- tbl_survfit(surv1,times=c(6,12,24),label_header = "**{time} Months**")
t2 <- tbl_survfit(surv1,probs=0.5,label_header = "**Median (months 95%CI)**")

tbl_merge(list(t1,t2), tab_spanner = FALSE)

mypal <- pal_jco("default")(10)[c(1,2,3,4,5,6,7,8)]

ggsurvplot(surv1 , data = data[data$Paper == "34",],
           title = " ",
           pval = T, pval.method = F,    # Add p-value &  method name
           palette = mypal,
           risk.table = T,                  # Add No at risk table
           cumevents = F,                   # Add cumulative No of events table
           tables.height = 0.15,               # Specify tables height
           tables.theme = theme_cleantable(),  # Clean theme for tables
           tables.y.text = F,
           conf.int = F, # Hide tables y axis text
           xlab= "Time (months)",
           ylab="Relapse-free Survival",
           pval.size=4.5,
           risk.table.title="N. at risk",
           risk.table.fontsize=5.5,
           font.y=c(22),
           font.tickslab=20,
           size=2,
           font.x=c(20),
           linetype=c(1,1,1,1,1,1,1,1,1),
           censor.size=6,
           # legend=c(0.8,1),           # Change legend titles
           # legend.labs = nam,  # Change legend labels
           # legend.title="",
           # font.legend=c(14,"bold"),
           break.time.by=3,
          surv.median.line="hv",
          xlim=c(0,26))





```